name: Code Style Check

on: [push, pull_request]

jobs:
  checkpatch:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install -y perl
        cd Tools/scripts/ && \
        wget https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl && \
        wget https://raw.githubusercontent.com/torvalds/linux/master/scripts/const_structs.checkpatch && \
        wget https://raw.githubusercontent.com/torvalds/linux/master/scripts/spelling.txt && \
        cd ../../

    - name: Run checkpatch.pl
      run: |
        git diff --name-only | grep -E "\.(c|h)$" | xargs -I {} perl ./Tools/scripts/checkpatch.pl --no-tree --file {}
